Feature us08 geolocation get datas
WildCodeSchool-2024-09/JS-Nantes-P2-WeartherForcast pull request #11
Opened 2024-11-14 14:39 UTC by EmiLy-Ly-san

2024-11-14 14:48 UTC, MrLootman commented
Un conflit avec fichier emptyheart.png

2024-11-15 14:47 UTC, MrLootman requested changes

2024-11-15 14:47 UTC, MrLootman commented on client/src/pages/GeolocaliseMe.tsx
> +            <linearGradient id="MyGradient">
Problème de nommage :
`MyGradient` devrait être `my-gradient`.

2024-11-18 14:48 UTC, EmiLy-Ly-san commented on client/src/pages/GeolocaliseMe.tsx
> +            <linearGradient id="MyGradient">
c'est fait !

2024-11-18 14:48 UTC, EmiLy-Ly-san commented
correction pushée

2024-11-19 09:05 UTC, MrLootman commented
Conflits sur deux fichiers à régler.

2024-11-19 09:16 UTC, MrLootman commented
Des conflits à régler

2024-11-19 15:10 UTC, EmiLy-Ly-san commented
Les conflits ont été résolus pour cette branche.

2024-11-20 08:08 UTC, MrLootman approved these changes

2024-11-20 08:08 UTC, merged