Feature/US02-WhatToWear
WildCodeSchool-2024-09/JS-Nantes-P2-WeartherForcast pull request #13
Opened 2024-11-15 13:55 UTC by CyrusWeir

Addition of a card component with recommendations for what to wear according to the weather.
Integrated:

- Data sets to verify weather and temperature conditions and define variables
- card component for the display of recommendations
- sources for icons
- conditional calling of images according to fetched API data.
- CSS for the display of component in the 'today.tsx' page.

2024-11-15 14:59 UTC, MrLootman requested changes

2024-11-15 14:59 UTC, MrLootman commented on client/src/components/WhatToWear.tsx
> +  // const [rain, setRain] = useState(0);
Beaucoup de code mort.
A supprimer avant intégration sur dev.

2024-11-15 14:59 UTC, MrLootman commented on client/src/components/WhatToWear.tsx
> +        // setRain(data.pop);
Tout le code mort doit être supprimé.

2024-11-15 14:59 UTC, MrLootman commented on client/src/components/WhatToWear.tsx
> +  }
Il serait bon d'isoler les interfaces dans un fichier `whatToWear.d.ts`.

2024-11-15 14:59 UTC, MrLootman commented on client/src/components/WhatToWear.tsx
> +
Code mort : A supprimer.

2024-11-15 14:59 UTC, MrLootman commented on client/src/components/WhatToWear.tsx
> +        />
Serait-il possible de mapper ces images, plutôt que de les appeler de cette façon ?

2024-11-18 14:47 UTC, CyrusWeir commented on client/src/components/WhatToWear.tsx
> +  // const [rain, setRain] = useState(0);
J'ai supprimé mon code commenté (pardon – j'avais l'intention de tout nettoyer vers la fin, mais, comme à la maison ; c'est plus facile de le faire petit à petit, tu as raison.)

2024-11-18 14:48 UTC, CyrusWeir commented on client/src/components/WhatToWear.tsx
> +        // setRain(data.pop);
Code supprimé 👍

2024-11-18 14:49 UTC, CyrusWeir commented on client/src/components/WhatToWear.tsx
> +  }
C'est fait - dans le dossier 'types' 👍

2024-11-18 14:49 UTC, CyrusWeir commented on client/src/components/WhatToWear.tsx
> +
Code supprimé 👍

2024-11-18 14:50 UTC, CyrusWeir commented on client/src/components/WhatToWear.tsx
> +        />
Tout mappé - ça a supprimé quelques lignes de code - j'aurais dû le faire depuis le début ! Merci de m'avoir mis sur la bonne piste.

2024-11-19 09:06 UTC, MrLootman approved these changes
👍

2024-11-19 09:07 UTC, merged