Feature us00 router correction
WildCodeSchool-2024-09/JS-Nantes-P2-WeartherForcast pull request #14
Opened 2024-11-18 16:16 UTC by EmiLy-Ly-san

Petite correction sur le router car je me suis rendue compte que je pointais Géolocalise me et Today sur le même endroit grosso modo, et je me demande si cela n'aidera pas pour la pull request en cours de Thibault. Donc il faudrait peut etre essayer d'incorporer ça avant la sienne pour qu'il soit à jour et tenter des choses. De même, il est possible qu'il est besoin de mes autres pull request en attente pour ce faire.
Merci d'avance,
Emilie

2024-11-18 16:20 UTC, MrLootman requested changes

2024-11-18 16:20 UTC, MrLootman commented on client/src/pages/GeolocaliseMe.tsx
> +            {/* <img src="" alt="" /> */}
Code mort.

2024-11-18 16:20 UTC, MrLootman commented on client/src/style/geolocaliseMe.css
> +  z-index: 110;
Pourquoi 110 ?

2024-11-18 16:23 UTC, EmiLy-Ly-san commented
Corrections faites, c'est pushé, merci !

2024-11-18 16:28 UTC, EmiLy-Ly-san commented
J'ai résolu les conflits avec dev

2024-11-19 09:17 UTC, MrLootman commented
Conflit avec App.css

2024-11-19 15:17 UTC, EmiLy-Ly-san commented
conflicts resolved

2024-11-19 15:18 UTC, EmiLy-Ly-san commented
non en fait jai pas fini ! sorry

2024-11-20 08:08 UTC, MrLootman commented
Conflits avec GeolocaliseMe

2024-11-20 09:30 UTC, EmiLy-Ly-san commented
conflits resolus , merci !

2024-11-20 10:05 UTC, Jeremy-Mrz approved these changes

2024-11-20 10:08 UTC, MrLootman approved these changes

2024-11-20 10:08 UTC, merged