Feature/us13 precipitation forecast
WildCodeSchool-2024-09/JS-Nantes-P2-WeartherForcast pull request #16
Opened 2024-11-20 10:02 UTC by Largoet

Creation de precipitationForecast.tsx et precipitationForecast.css
Ajout du composant "precipitationForecast" à la page Today.tsx
Apporte des précisions sur les précipitations prévues dans les trois prochaines heures. 
j'attire votre attention sur le fait que today.tsx à des modifications propre à la dernière pull request ayant été refusé pour raison d'un bug sur la geoloc.

2024-11-20 10:19 UTC, Largoet commented
Le git pull dev sur "Feature/us13 precipitation forecast" et le merge en local a bien été effectué.

2024-11-20 11:29 UTC, Largoet commented
Vu avec Jeremy, création d'un bouton pour refresh la geoloc sur la page today.
la page "geolocaliseMe" est menée à disparaitre.

2024-11-20 14:15 UTC, MrLootman requested changes

2024-11-20 14:15 UTC, MrLootman commented on client/src/pages/Today.tsx
> +  setCity: (value: string) => void;
Cette interface existe déjà dans `PrecipitationForecast`.
Il y a donc répétition de code entre les fichiers.
Il s'agira pour toi / vous de réunir les interfaces dans des fichiers à part, ce qui permettra de réutiliser le code et d'éviter les duplications inutiles.
C'est exactement comme pour le sélecteur `*` écrit entre différent fichier.

2024-11-20 14:28 UTC, Largoet commented on client/src/pages/Today.tsx
> +  setCity: (value: string) => void;
Ok reçu, je m'occupe de ça ! Merci.

2024-11-20 16:10 UTC, Largoet commented
Creation de Outletcontext.d.ts et import dans les pages le nécessitant. 
Correction d'une faute de frappe dans le nom de PrecipitationForcast.ccs et .tsx

2024-11-21 13:55 UTC, MrLootman approved these changes

2024-11-21 13:57 UTC, MrLootman approved these changes

2024-11-21 13:57 UTC, merged