Feature us04 favorites cities style
WildCodeSchool-2024-09/JS-Nantes-P2-WeartherForcast pull request #17
Opened 2024-11-21 13:46 UTC by EmiLy-Ly-san

2024-11-22 09:03 UTC, MrLootman commented
Tentative de fusion avec main. A modifier.

2024-11-22 09:10 UTC, EmiLy-Ly-san commented
Oh ça veut pas rentrer, desolée ! j'ai changé pour dev

2024-11-22 09:10 UTC, EmiLy-Ly-san commented
je regle les conflits d'abord

2024-11-22 09:16 UTC, EmiLy-Ly-san commented
Voila c'est fait, conflicts resolved. Merci !

2024-11-26 10:52 UTC, Jeremy-Mrz requested changes

2024-11-26 10:52 UTC, Jeremy-Mrz commented on client/src/components/Footer.tsx
> +        </NavLink>
Il n'y a pas de raison d'utiliser des `NavLink` dans ce cas, tu peux simplement utiliser des `Link`

2024-11-26 10:52 UTC, Jeremy-Mrz commented on client/src/components/FavoriteCityCard.tsx
> +        <div className="rubbish-bin-container">
Attention, tu utilises des noms de tag en tant que classe `header` & `footer` dans des divs. Il faut utiliser les tags HTML adapté, comme ça tu pourra éviter le multiplication de classe et utiliser des CSS selectors du genre 
`.ctiy-favorite-card header` ou `.ctiy-favorite-card footer`

2024-11-26 10:52 UTC, Jeremy-Mrz commented on client/src/components/WhatToWear.tsx
> +              className="wearIcon"
Le nom des classes est à écrire en kebab-case `wear-icon`

2024-11-26 10:52 UTC, Jeremy-Mrz commented on client/src/components/WhatToWear.tsx
> +              className="wearIcon"
idem

2024-11-26 10:52 UTC, Jeremy-Mrz commented on client/src/pages/GeolocaliseMe.tsx
> +  }); //undefined parce qu"il est nul au depart
Si la valeur est `null`, n'est-il pas possible d'utiliser `null` ?

2024-11-26 10:52 UTC, Jeremy-Mrz commented on client/src/pages/MyCities.tsx
> +      </div>
Il me semble que tu as un `<div>` superflu. 
Ne pas hésiter à utiliser des CSS selector pour éviter la multiplications des classes 
`.container-header div {....`

2024-11-26 10:52 UTC, Jeremy-Mrz commented on client/src/pages/Today.tsx
> +  // biome-ignore lint/correctness/useExhaustiveDependencies: <explanation> //TODO: find a better solution !
Il me semble que l'erreur à été corrigé dans une autre PR

2024-11-26 10:52 UTC, Jeremy-Mrz commented on client/src/pages/Today.tsx
> +  const handleClick = () => {};
?

2024-11-26 10:52 UTC, Jeremy-Mrz commented on client/src/style/myCities.css
> +.iconFavoritesOnTitle {
Le nom des classes doit être en kebab-case

2024-11-26 11:07 UTC, EmiLy-Ly-san commented on client/src/components/Footer.tsx
> +        </NavLink>
Ba c'est que ca me permet d'utiliser automatiquement la calle active donc j'aimerais bien les garder si possible, c'est hyper pratique

2024-11-26 11:09 UTC, EmiLy-Ly-san commented on client/src/components/FavoriteCityCard.tsx
> +        <div className="rubbish-bin-container">
Ah ok, je trouvais ça pas mal pour décortiquer la card, je peux à la place directement les tags header et footer dans la section à la place des div correspondantes, c'est ça ?Merci d'avance pour ta réponse

2024-11-26 11:09 UTC, EmiLy-Ly-san commented on client/src/components/WhatToWear.tsx
> +              className="wearIcon"
oupsi! je vais changer ça

2024-11-26 11:15 UTC, EmiLy-Ly-san commented on client/src/components/WhatToWear.tsx
> +              className="wearIcon"
changement fait

2024-11-26 11:15 UTC, EmiLy-Ly-san commented on client/src/components/WhatToWear.tsx
> +              className="wearIcon"
changement fait

2024-11-26 11:18 UTC, EmiLy-Ly-san commented on client/src/pages/GeolocaliseMe.tsx
> +  }); //undefined parce qu"il est nul au depart
J'ai laissé cette page pour l'instant car le code intéressait mes camarades pour comprendre des notions, mais cette page n'est pas utilisé finalement, elle est vouée à etre definitivement supprimée. Ok en tout cas en effet je devrais utiliser null c'est sur. Du coup je ne fais pas de changement.

2024-11-26 11:20 UTC, EmiLy-Ly-san commented on client/src/pages/MyCities.tsx
> +      </div>
De quelle div parles-tu? le container-title ? oui si je comprends bien j'ai juste à mettre le style CSS de container-title dans celui de container-header en fait ! Bon je vais corriger ça cette après midi. Merci

2024-11-26 11:20 UTC, EmiLy-Ly-san commented on client/src/pages/Today.tsx
> +  // biome-ignore lint/correctness/useExhaustiveDependencies: <explanation> //TODO: find a better solution !
oui ! je vais replacer la correction ici du coup

2024-11-26 11:21 UTC, EmiLy-Ly-san commented on client/src/pages/Today.tsx
> +  const handleClick = () => {};
oups! J'aurais du commenter ici pour dire un genre de TODO de la fonctionnalités d'après. Je vais l'enlever du coup

2024-11-26 11:22 UTC, EmiLy-Ly-san commented on client/src/style/myCities.css
> +.iconFavoritesOnTitle {
oki je change ça , pour changer ! Il y a des trucs qui rentrent pas ! Désolée...

2024-11-26 13:52 UTC, Jeremy-Mrz commented on client/src/components/Footer.tsx
> +        </NavLink>
👍

2024-11-26 13:53 UTC, Jeremy-Mrz commented on client/src/components/FavoriteCityCard.tsx
> +        <div className="rubbish-bin-container">
Niveau accessibilité et lisibilité du code, il est préférable d'utiliser les tags html appropriés. 
Oui c'est tout à fait ça 👍

2024-11-26 13:55 UTC, Jeremy-Mrz commented on client/src/pages/MyCities.tsx
> +      </div>
Oui le container title

2024-11-26 13:55 UTC, Jeremy-Mrz commented on client/src/pages/GeolocaliseMe.tsx
> +  }); //undefined parce qu"il est nul au depart
Ca marche

2024-11-26 13:55 UTC, Jeremy-Mrz commented on client/src/pages/Today.tsx
> +  // biome-ignore lint/correctness/useExhaustiveDependencies: <explanation> //TODO: find a better solution !
👍

2024-11-26 13:56 UTC, Jeremy-Mrz commented on client/src/pages/Today.tsx
> +  const handleClick = () => {};
👍

2024-11-26 13:56 UTC, Jeremy-Mrz commented on client/src/style/myCities.css
> +.iconFavoritesOnTitle {
Pas de soucis

2024-11-26 15:06 UTC, EmiLy-Ly-san commented on client/src/components/Footer.tsx
> +        </NavLink>
Du coup je laisse comme ça ?

2024-11-26 15:06 UTC, EmiLy-Ly-san commented on client/src/components/FavoriteCityCard.tsx
> +        <div className="rubbish-bin-container">
oki je vais faire ça alors

2024-11-26 15:06 UTC, EmiLy-Ly-san commented on client/src/pages/MyCities.tsx
> +      </div>
ok ça marche, je corrige ça! Merci

2024-11-26 15:31 UTC, Jeremy-Mrz commented on client/src/components/Footer.tsx
> +        </NavLink>
Tu peux si tu utilise la classe `active` oui

2024-11-26 15:34 UTC, EmiLy-Ly-san commented on client/src/components/FavoriteCityCard.tsx
> +        <div className="rubbish-bin-container">
Ah finalement, ça se mêle avec le style general du vrai header de l'appli et du vrai footer.. Du coup j'ai gardé le nom des classes mais j'ai changé section pour article, ce qui me permet de remplacer certaine div (header card et footercard) par des sections. Je fais un genre de compromis si cela te va

2024-11-26 16:13 UTC, EmiLy-Ly-san commented
Normalement j'ai fini toutes les corrections, merci !

2024-11-27 08:25 UTC, Jeremy-Mrz approved these changes

2024-11-27 08:25 UTC, merged