Feature/us15 dot env
WildCodeSchool-2024-09/JS-Nantes-P2-WeartherForcast pull request #18
Opened 2024-11-21 15:42 UTC by Largoet

Intégration du .env et modification des liens vers l'API dans les variables situés dans Today.tsx - PrecipitationForcast.tsx - GeocalismeMe.tsx  et WhatToWear.tsx
Traduction du Français vers l'Anglais PrecipitationForcast.tsx

2024-11-21 16:06 UTC, Jeremy-Mrz requested changes

2024-11-21 16:06 UTC, Jeremy-Mrz commented on client/src/components/WhatToWear.tsx
> +  const url = `https://api.openweathermap.org/data/2.5/weather?q=${city}&appid=${import.meta.env.VITE_OPENWEATHER_API_KEY}&units=metric`;
retire `VITE` du nom de ta clé

2024-11-21 16:06 UTC, Jeremy-Mrz commented on client/src/pages/GeolocaliseMe.tsx
> +      const urlforCity: string = `https://api.openweathermap.org/data/2.5/weather?q=${outletContext.city}&appid=${import.meta.env.VITE_OPENWEATHER_API_KEY}&units=metric`;
Idem

2024-11-21 16:06 UTC, Jeremy-Mrz commented on client/src/pages/Today.tsx
> +      const url = `https://api.openweathermap.org/data/2.5/weather?q=${outletContext.city}&appid=${import.meta.env.VITE_OPENWEATHER_API_KEY}&units=metric`;
Idem

2024-11-21 16:06 UTC, Jeremy-Mrz commented on client/src/components/PrecipitationForcast.tsx
> +      const url = `https://api.openweathermap.org/data/2.5/forecast?q=${outletContext.city}&cnt=1&appid=${import.meta.env.VITE_OPENWEATHER_API_KEY}`;
Retires `VITE` du nom de ta clé

2024-11-21 16:17 UTC, Largoet commented
Done !

2024-11-22 09:11 UTC, Jeremy-Mrz requested changes

2024-11-22 09:11 UTC, Jeremy-Mrz commented on client/.env.sample
>  # Other Environment Variables (if needed)
Retire aussi  `VITE` de ton .env.sample

2024-11-22 09:18 UTC, Largoet commented on client/.env.sample
>  # Other Environment Variables (if needed)
Ah ! curieux, je pensais l'avoir fait ! je change ça immédiatement ! Mea Culpa

2024-11-22 09:35 UTC, Jeremy-Mrz approved these changes

2024-11-22 09:35 UTC, merged