Feature/us 10 weathernews
WildCodeSchool-2024-09/JS-Nantes-P2-WeartherForcast pull request #20
Opened 2024-11-22 08:22 UTC by Julien-44100

Envoi de la carte weathernews avec css associé.

2024-11-22 09:12 UTC, MrLootman requested changes

2024-11-22 09:12 UTC, MrLootman commented on client/src/App.css
Code mort. A supprimer.

2024-11-22 09:12 UTC, MrLootman commented on client/src/style/weathernews.css
> +  color: #61aeff;
Le h2 ne doit pas être invoqué en l'état, sans spécifier dans quel conteneur il se situe.
En l'état, tous les h2 du site ont les propriétés que tu lui ajoutes.
Pour finir, on ne met pas de `display: flex` sur un élément enfant. A revoir.

2024-11-22 09:12 UTC, MrLootman commented on client/src/pages/WeatherNews.tsx
> +        <div className="title">
Ces className sont "dangeureuses".
1. La className "element" est trop générique pour être employée. Tu es dans un composant nommé "WeatherNews", pourquoi ne pas appeler ta classe "weather-news" ?
2. Ajouter une classe "header" à un élément de DOM situé dans un fichier `WeatherNews.tsx`, ça présage d'un conflit avec un composant header à plein nez.
3. L'utilisation des `div` en cascade doit être évité au maximum, pour des raisons d'accessibilité essentiellement. Est-il nécessaire d'avoir autant d'éléments conteneurs ? Si oui, quels éléments HTML seraient plus sémantiques ?

2024-11-27 11:13 UTC, Julien-44100 commented
conflit résolut

2024-11-27 13:22 UTC, Julien-44100 commented
dev pullé pour la mise à jour de la branche pres a etre merger

2024-11-28 11:22 UTC, closed without merging