Feature/us09 preferences
WildCodeSchool-2024-09/JS-Nantes-P2-WeartherForcast pull request #21
Opened 2024-11-22 10:26 UTC by CyrusWeir

J'ai travaillé plus les pages de 'préférences'. J'ai ajouté plus d'inputs, et j'ai intégré ces données dans un outlet context.
Au fil du travail, j'ai ajouté une page dans le router pour avoir plus d'informations sur les conseils vestimentaires, et j'ai commencé à ajouter plus de data pour faire une comparaison (tout ceci a été validé avec l'équipe pendant un daily toast). Je me suis rendu compte que ça mérite peut-être une nouvelle branche... du coup... voici un pull request pour ajouter ce que j'ai déjà fait... désolé pour le manque d'éveil - je suis bien conscient que ceci n'est pas un pull request bien propre comme il faut ; je mélange deux gros tickets ici... mais j'apprends... je vous jure.

2024-11-22 13:32 UTC, MrLootman requested changes

2024-11-22 13:32 UTC, MrLootman commented on client/src/assets/Humidity.tsx
Attention à l'extension ici :

Les fichiers `.tsx` concernent les composants, c'est-à-dire les fonctions qui retournent des éléments `.tsx`.

ce fichier (Humidity) contient un tableau que tu exportes. Ce n'est donc pas un fichier `.tsx`, mais `.ts`.

2024-11-22 13:32 UTC, MrLootman commented on client/src/pages/PreferenciesWear.tsx
> +
**Problème ici** : Les deux fonctions sont identiques. Il y a donc répétition de code. L'une des fonctions est donc superflue.

2024-11-22 13:32 UTC, MrLootman commented on client/src/components/WhatToWear.tsx
>    const [conditID, setConditID] = useState(615);
Cette façon d'importer les interfaces, à savoir `WhatToWearInterfaces.useStateProps` est beaucoup trop lourde.

Je te laisse regarder mon commentaire dans le fichier concernant les interfaces.

2024-11-22 13:32 UTC, MrLootman commented on client/src/types/whatToWear.d.ts
>  export default WhatToWearInterfaces;
Plutôt que d'exporter `WhatToWearInterfaces`, ce qui exportera un objet qui wrappera tes deux interfaces, tu ferais mieux d'exporter simplement chaque interface individuellement.

`export interface OutletContextProps`.

Si bien que dans les fichiers où elles sont appelées, tu pourras les importer comme suit :

`import { OutletContextProps } from "../......"`.

2024-11-22 13:32 UTC, MrLootman commented on client/src/types/whatToWear.d.ts
>  interface weatherConditionItemProps {
Attention : cette interface doit être écrite en PascalCase, et non en camelCase.

2024-11-22 13:32 UTC, MrLootman commented on client/src/pages/WhatToWearMore.tsx
> +import type WhatToWearInterfaces from "../types/whatToWear";
Voir mon commentaire sur l'import d'interfaces.

2024-11-27 13:17 UTC, CyrusWeir commented on client/src/assets/Humidity.tsx
J'ai changé tous les fichiers tableau pour des .ts

2024-11-27 13:19 UTC, CyrusWeir commented on client/src/pages/PreferenciesWear.tsx
> +
La deuxième fonction vérifie le status 'checked' pour les checkboxes - j'ai essayé d'enregistrer le boolean en tant que 'value', mais ça n'a pas marché... mais je suis preneur s'il y a une meilleure méthode!

2024-11-27 13:23 UTC, CyrusWeir commented on client/src/components/WhatToWear.tsx
>    const [conditID, setConditID] = useState(615);
J'ai essayé de changer les imports comme cité ici. Je crois qu'il y a du cleaning à faire de mon côté sur les fichiers 'types'... mais j'essaie de mettre toutes les fonctionnalités possibles vu que le grand jour arrive à grands pas (je suis vraiment désolé pour la quantité de nouveautés ajoutée avec ce 2ᵉ push - je sais que j'ai un peu foiré d'appliquer les bonnes pratiques du workflow - ce sont des gros morceaux de code presque incompréhensible à cause de la quantité ; c'est un point à améliorer de mon côté 😬)

2024-11-27 13:25 UTC, CyrusWeir commented on client/src/types/whatToWear.d.ts
>  export default WhatToWearInterfaces;
Je crois que j'ai appliqué cette méthodologie partout dans mes fichiers 🤞

2024-11-27 13:38 UTC, EmiLy-Ly-san reviewed
Attention, cette branche ne travaille pas sur le dev à jour....

2024-11-27 13:38 UTC, EmiLy-Ly-san commented on client/src/App.tsx
Je me dis qu'on aurait pu faire plusieurs contexts selon les besoins, genre un pour les preferences wear par exemple, et un autre pour les variables plus globales. Bref, si on a le temps, on nettoieraà la fin, pour l'instant ça peut rester comme ça.

2024-11-27 13:46 UTC, EmiLy-Ly-san commented on client/src/App.tsx
Attention aussi, au nommage "outlet' utilisé dans les types de tes composants, cela crée une confusion avec le veritable outletContext, de meme tu peux utiliser le vrai outletContext pour les variables qui sont dedans, plutot que de les remettre ( en doublon) dans tes types de tes composants

2024-11-27 14:04 UTC, MrLootman requested changes
**L'immense problème que pose cette branche :**

J'ai effectué une review avec 16 commentaires, donc 16 endroits potentiels où il te faut améliorer le code.

Le fait d'avoir continué sur ta branche de travail te met dans un perpétuel décalage, et rend la branche quasiment impossible à intégrer. En effet, à chaque fois que tu décides de continuer à travailler dessus, tu réintègres du travail que je n'ai pas évalué.

**Par conséquent** : Il faut **arrêter de travailler sur cette branche, se contenter de prendre en compte les commentaires pour que l'intégration sur `dev` puisse se faire**.

**A noter** : Dans le cadre d'un projet 3, il y aura invalidation de ce type de Pull Request, en ce que ça ne respecte **ni le Git Workflow, ni la méthodologie Scrum**.

2024-11-27 14:04 UTC, MrLootman commented on client/src/assets/Wind.ts
> +  { Direction: "North-Northwesterly,", start: 292.5, end: 337.5 },
Une clé d'objet écrite en PascalCase ne respecte pas les conventions de nommage en JavaScript.
`Direction` devrait être écrit `direction`.

2024-11-27 14:04 UTC, MrLootman commented on client/src/components/WhatToWear.tsx
> +import type { wtwProps } from "../types/whatToWear";
Tu n'as pas besoin d'appeler les types individuellement.
Tu peux les enchaîner :

`import type { OutletContextProps, WeatherConditionImagesProps, ... }`

2024-11-27 14:04 UTC, MrLootman commented on client/src/components/WhatToWear.tsx
> +  const city = useOutletContext<OutletContextProps>().city;
Pour augmenter la lisibilité de ton composant, mieux vaudrait préférer la destructuration :

`const { clothingPref, city } = useOutletContext<OutletContextProps>()`

2024-11-27 14:04 UTC, MrLootman commented on client/src/pages/PreferenciesWear.tsx
> +
Faute de temps, je ne te demande pas une refactorisation à cet endroit. Dans l'idéal, il aurait fallut une seule fonction capable de faire les deux traitement (et pour les input, et pour les checkbox).
Et dans un monde encore plus idéal, il aurait fallut ne pas dépendre des states (mais ça, on voit ça demain)

2024-11-27 14:04 UTC, MrLootman commented on client/src/pages/PreferenciesWear.tsx
> +          />{" "}
Cette string vide est à retirer.

2024-11-27 14:04 UTC, MrLootman commented on client/src/pages/PreferenciesWear.tsx
> +          <label htmlFor="bike">go bike riding</label>
L'attribut `htmlFor` n'est pas un texte alternatif, mais une ancre permettant de relier un label et un input.
Autremement dit, si la valeur `bike` est attribuée ici, il faut que l'input suivant possède l'attribut `name` avec pour valeur `bike` également.

Ce commentaire est valable pour tous les attributs `htmlFor` écrits ci-dessous.

2024-11-27 14:04 UTC, MrLootman commented on client/src/pages/Today.tsx
> +  const [conditions, setConditions] = useState<string>("descritpion");
Faute d'orthographe à "description"

2024-11-27 14:04 UTC, MrLootman commented on client/src/pages/Today.tsx
> +    useOutletContext<OutletContextProps>();
Les trois exécutions de `useOutletContext` pourraient être réunies en une seule variable.

2024-11-27 14:04 UTC, MrLootman commented on client/src/pages/Today.tsx
>    // biome-ignore lint/correctness/useExhaustiveDependencies: <explanation> //TODO: find a better solution !
Justement, oui : trouve une meilleure solution 🌞

2024-11-27 14:04 UTC, MrLootman commented on client/src/pages/Today.tsx
> +  console.warn("newHumidity", newHumidity);
Ces `console.warn` ne doivent pas être fusionnés sur `dev`.

2024-11-27 14:04 UTC, MrLootman commented on client/src/pages/WhatToWearMore.tsx
> +import type { windCounselProps } from "../types/preferencesWear";
Pareil que précédemment : Tu devrais réunir ces quatres dernières lignes en un unique import.

2024-11-27 14:04 UTC, MrLootman commented on client/src/pages/WhatToWearMore.tsx
> +  const { wind } = useOutletContext<cityOutletContextType>();
Tu déclares beaucoup trop de variables. Ces quatre dernières variables pourraient être réduites à une seule.

2024-11-27 14:04 UTC, MrLootman commented on client/src/pages/WhatToWearMore.tsx
> +      console.warn("prefHumidRealFeel", prefHumidRealFeel);
console.warn à supprimer.

2024-11-27 14:04 UTC, MrLootman commented on client/src/pages/WhatToWearMore.tsx
> +  console.warn("windRange:", windRange);
🤨

2024-11-27 14:04 UTC, MrLootman commented on client/src/pages/WhatToWearMore.tsx
> +    </>
Ce composant est particulièrement illisible. Dans l'idéal, il faudrait le refactoriser pour le rendre intelligible.

2024-11-27 14:04 UTC, MrLootman commented on client/src/types/whatToWear.d.ts
>  }
Les interfaces `weatherConditionItemProps et WeatherConditionImagesProps` partagent les mêmes caractéristiques. Une refactorisation est à prévoir.

2024-11-27 15:07 UTC, CyrusWeir commented on client/src/pages/PreferenciesWear.tsx
> +
Merci - j'avais vu quelquechose sur les inputs non-controllé - mais je ne me suis pas lancé dedans.

2024-11-27 15:09 UTC, CyrusWeir commented on client/src/App.tsx
J'ai fait des modifs pour que ça soit un peu plus lisible. Merci pour ton feedback. Je suis preneur pour tout amelioration de mon code ;)

2024-11-27 15:27 UTC, MrLootman approved these changes

2024-11-27 15:27 UTC, merged