Feature/us 14 daybyday
WildCodeSchool-2024-09/JS-Nantes-P2-WeartherForcast pull request #27
Opened 2024-11-27 13:11 UTC by Julien-44100

2024-11-27 15:22 UTC, MrLootman requested changes

2024-11-27 15:22 UTC, MrLootman commented on client/src/pages/DayByDay.tsx
> +  // const [moredata, setData] = useState("");
A travers les 9 fichiers modifiés, il faut impérativement **supprimer le code mort**, c'est-à-dire tout le code qui ne sera pas exécuté.

2024-11-27 15:22 UTC, MrLootman commented on client/src/pages/DayByDay.tsx
> +        // setData(data);
Code mort. A supprimer.

2024-11-27 15:22 UTC, MrLootman commented on client/src/pages/DayByDay.tsx
> +  };
Les cinq fonctions ci-dessus sont identiques, à ceci près que le chiffre par lequel tu multiplies ton paramètre change.

Tu dois pouvoir factoriser ton code pour n'avoir qu'une seule fonction, appelées avec deux arguments : le premier qui s'appelerait `temperature`, le deuxième `multiplier`.

2024-11-27 15:22 UTC, MrLootman commented on client/src/pages/DayByDay.tsx
> +          <div className="datebdb">{firstlettre}</div>
Le problème majeur ici : le nommage des classes.
`datebdb` n'est pas un nom clair.
Pour rappel : La convention d'écriture en JavaScript est le `camelCase`.

2024-11-27 15:22 UTC, MrLootman commented on client/src/pages/DayByDay.tsx
> +          <div className="datebdb">{secondnumber}</div>
Tu utilises un élément `div` pour faire apparaître du texte, ce qui est incorrect. Les éléments `div` ne doivent servir qu'à conteneuriser d'autres éléments HTML.

2024-11-27 15:22 UTC, MrLootman commented on client/src/pages/DayByDay.tsx
> +          <section className="tempsminandrectangle">
Problème de nommage de classe.

2024-11-27 15:22 UTC, MrLootman commented on client/src/pages/DayByDay.tsx
> +                  // width: calculateDimensions(temperature).width,
Code mort.

2024-11-27 15:22 UTC, MrLootman commented on client/src/pages/DayByDay.tsx
> +        <div className="temperaturemaxdbd">{temperature4}°</div>
Toujours un problème de nommage des classes. A modifier partout où tu n'utilises pas la convention `kebab-case`.

2024-11-27 15:22 UTC, MrLootman commented on client/src/style/DayByDay.css
> +img {
L'utilisation de la balise `img` de cette manière est dangereuse. Tu dois augmenter la spécificité pour bien attraper les `img` du composant DayByDay, et non ceux du projet intégral.

2024-11-27 15:22 UTC, MrLootman commented on client/src/style/DayByDay.css
> +/* figcaption {
Code mort.

2024-11-27 15:22 UTC, MrLootman commented on client/src/style/DayByDay.css
> +  /* margin-right: 30px; */
Code mort.

2024-11-27 15:22 UTC, MrLootman commented on client/src/style/DayByDay.css
> +  /* margin-top: 20px; */
Code mort.

2024-11-28 11:02 UTC, Julien-44100 commented
J'ai fait tout les corrections ses près à merger

2024-11-28 11:10 UTC, MrLootman requested changes
La dernière revue ne se concentre que sur des éléments de syntaxe.
Il est important que ton code soit respectueux de la convention camelCase.
Bien joué pour la refactorisation de ta fonction `calculateDimensions`.

2024-11-28 11:10 UTC, MrLootman commented on client/src/pages/DayByDay.tsx
>    const firstlettre1 = Array.from(dayname1)[0];
Ce n'est toujours pas du `camelCase`. D'ailleurs, les cinq variables ne sont pas en camelCase. A modifier.

2024-11-28 11:10 UTC, MrLootman commented on client/src/pages/DayByDay.tsx
> +          <p>{temperaturemin1}°</p>
Beaucoup de variables ne sont pas écrites selon la convention camelCase.
Il est important de corriger ça avant de merger ta branche avec dev.

2024-11-28 11:21 UTC, MrLootman approved these changes
👍

2024-11-28 11:21 UTC, merged