Feature/us16 sun rotation
WildCodeSchool-2024-09/JS-Nantes-P2-WeartherForcast pull request #29
Opened 2024-11-27 14:51 UTC by Largoet

2024-11-27 14:59 UTC, MrLootman requested changes

2024-11-27 14:59 UTC, MrLootman commented on client/src/pages/Today.tsx
>        //currentFavorites pour lui dire de regarder d"abord le contenu courant de favorites et de le modifier avant de faire la suite. Ca garantie qu"on prenne bien la valeur telle auelle est au momem
Le commentaire est flou, et présente des doubles quotes et des fautes d'orthographe. A corriger.

2024-11-27 14:59 UTC, MrLootman commented on client/src/pages/Today.tsx
> +          // outletContext.setIdCity(data.id); // ℹ️ For the favorites gestion
Code mort. A supprimer.

2024-11-27 14:59 UTC, MrLootman commented on client/src/utilitiesFunctions/getWeatherIcons.tsx
> +  const weahterIconToFind = weatherIconsData.find((weatherIcon) => {
Faute d'orthographe.
Le nom devrait être 
```typescript
weatherIconToFind
```

2024-11-27 15:25 UTC, Largoet commented on client/src/utilitiesFunctions/getWeatherIcons.tsx
> +  const weahterIconToFind = weatherIconsData.find((weatherIcon) => {
Vu merci !

2024-11-28 14:35 UTC, MrLootman approved these changes

2024-11-28 14:35 UTC, merged