Feature us00 rooting
WildCodeSchool-2024-09/JS-Nantes-P2-WeartherForcast pull request #3
Opened 2024-11-08 14:54 UTC by Jeremy-Mrz

2024-11-08 15:13 UTC, Largoet approved these changes

2024-11-12 08:40 UTC, MrLootman requested changes

2024-11-12 08:40 UTC, MrLootman commented on client/src/main.tsx
Le router est écrit directement dans le fichier `main.tsx`. 
Dans le soucis de "séparer les préoccupations", il serait bien de l'isoler dans un fichier `router.tsx`.

2024-11-12 08:40 UTC, MrLootman commented on client/src/App.css
> +  /* margin: 8px; */
Une ligne de style commentée ne doit pas être maintenue dans le code. Il faut soit la supprimer, soit décrire pourquoi elle gagne à être maintenue.

2024-11-12 08:40 UTC, MrLootman commented on client/src/App.css
> +  flex-shrink: 1 0 auto;
Si on commente cette ligne `flex-shrink` dans la console du navigateur, que se passera-t-il visuellement ?

2024-11-12 08:40 UTC, MrLootman commented on client/src/App.css
> +  width: 100vw;
Pour éviter deux règles de margin à gauche et à droite, il serait préférable de viser un :
`margin: 0 auto;`

2024-11-12 08:40 UTC, MrLootman commented on client/src/App.css
> +  flex-shrink: 0;
Idem que pour le commentaire précédent.

2024-11-12 09:41 UTC, EmiLy-Ly-san commented on client/src/App.css
> +  /* margin: 8px; */
oki c'est delete.

2024-11-12 09:42 UTC, EmiLy-Ly-san commented on client/src/App.css
> +  flex-shrink: 1 0 auto;
oui en fait j'ai utilisé une autre méthode, c'est pour un sticky footer

2024-11-12 09:42 UTC, EmiLy-Ly-san commented on client/src/App.css
> +  width: 100vw;
ok j'ai mis ça du coup , merci !

2024-11-12 10:01 UTC, MrLootman approved these changes
👍

2024-11-12 10:01 UTC, merged