Feature us03 navigation
WildCodeSchool-2024-09/JS-Nantes-P2-WeartherForcast pull request #4
Opened 2024-11-12 10:20 UTC by EmiLy-Ly-san

2024-11-12 15:37 UTC, MrLootman requested changes
Tentative de fusion avec `main`.

2024-11-12 16:00 UTC, EmiLy-Ly-san commented
ah mon dieu désolée

2024-11-12 16:10 UTC, MrLootman requested changes
Partout où les className sont écrits en camelCase, il faut passer en kebab-case

2024-11-12 16:10 UTC, MrLootman commented on client/src/style/header.css
> +.navBar {
Attention : Le kebab-case est requis pour les nommages d'id et de className

2024-11-12 17:12 UTC, EmiLy-Ly-san commented on client/src/style/header.css
> +.navBar {
Les changements on été fait pour cette branche

2024-11-13 10:34 UTC, MrLootman approved these changes

2024-11-13 10:34 UTC, merged