Feature us08 geolocation
WildCodeSchool-2024-09/JS-Nantes-P2-WeartherForcast pull request #6
Opened 2024-11-12 10:26 UTC by EmiLy-Ly-san

2024-11-12 15:38 UTC, MrLootman requested changes
Tentative de fusion avec `main`

2024-11-12 17:26 UTC, EmiLy-Ly-san commented
J'ai changé les classeName en kebab-case

2024-11-13 10:39 UTC, MrLootman commented
Attention : Conflits avec le fichier Router.

2024-11-13 10:45 UTC, EmiLy-Ly-san commented
J'ai bien pullé dev donc plus de conflit

2024-11-13 16:35 UTC, MrLootman approved these changes

2024-11-13 16:35 UTC, MrLootman commented on client/src/style/animationCircle.css
> +.animationCircles {
Attention : La convention de nommage en CSS est le kebab-case.

2024-11-13 16:35 UTC, merged