Feature us01 background dynamic
WildCodeSchool-2024-09/JS-Nantes-P2-WeartherForcast pull request #7
Opened 2024-11-12 10:56 UTC by EmiLy-Ly-san

2024-11-12 15:42 UTC, MrLootman requested changes
Tentative de fusion avec `main`

2024-11-12 17:27 UTC, EmiLy-Ly-san commented
J'ai changé les classeName en kebab-case

2024-11-12 17:48 UTC, EmiLy-Ly-san commented
@MrLootman J'ai résolu les conflits avec dev que j'ai ramené

2024-11-14 09:13 UTC, EmiLy-Ly-san commented
Conflicts resolved

2024-11-14 13:14 UTC, MrLootman requested changes

2024-11-14 13:14 UTC, MrLootman commented on client/src/assets/images/rain.jpg
Presque 1mo la photo ? Je pense qu'il y a moyen de la compresser sans que ça n'entache la qualité.
---> https://squoosh.app/

2024-11-14 13:14 UTC, MrLootman commented on client/src/style/searchBar.css
>  }
Dans ce fichier `searchBar.css`, tu utilises la balise `form` de manière non spécifique.
Ce qui veut dire que tous les formulaires potentiels de l'application vont être touché par ce code.
Il faut augmenter la spécificité, en ciblant plus précisément les éléments.

2024-11-14 13:28 UTC, EmiLy-Ly-san commented on client/src/assets/images/rain.jpg
ah oui en effet

2024-11-14 13:28 UTC, EmiLy-Ly-san commented on client/src/style/searchBar.css
>  }
ah mince, je change ça. Merci !

2024-11-14 15:59 UTC, MrLootman approved these changes

2024-11-14 15:59 UTC, merged