Feature us03 nav bar animation link hover
WildCodeSchool-2024-09/JS-Nantes-P2-WeartherForcast pull request #8
Opened 2024-11-13 14:39 UTC by EmiLy-Ly-san

2024-11-14 09:29 UTC, Largoet reviewed
ça m'a l'air clair.

2024-11-14 16:04 UTC, EmiLy-Ly-san commented
mis à jour avec un pull dev

2024-11-15 14:43 UTC, MrLootman requested changes
Les sélecteurs CSS sont bien écrits, la spécificité est bonne !
Quelques changements en terme de règles de nommage, et la branche pourra être intégrée.

2024-11-15 14:43 UTC, MrLootman commented on client/src/pages/GeolocaliseMe.tsx
> +// client\src\style\animationCircle.css
Code mort. A supprimer.

2024-11-15 14:43 UTC, MrLootman commented on client/src/pages/GeolocaliseMe.tsx
> +    <section className="circleContainer">
className écrite en camelCase. Or, la convention est le kebab-case.

2024-11-15 14:43 UTC, MrLootman commented on client/src/pages/GeolocaliseMe.tsx
> +          <linearGradient id="MyGradient">
id écrit en PascalCase. Or, la convention est le camelCase.

2024-11-18 14:41 UTC, EmiLy-Ly-san commented on client/src/pages/GeolocaliseMe.tsx
> +// client\src\style\animationCircle.css
ok c'est supprimé

2024-11-18 14:41 UTC, EmiLy-Ly-san commented on client/src/pages/GeolocaliseMe.tsx
> +    <section className="circleContainer">
desolée, j'ai modifié

2024-11-18 14:41 UTC, EmiLy-Ly-san commented on client/src/pages/GeolocaliseMe.tsx
> +          <linearGradient id="MyGradient">
encore desolée, j'ai modifié

2024-11-18 14:42 UTC, EmiLy-Ly-san commented
j'ai pusher mes corrections apres un pull dev

2024-11-18 16:21 UTC, MrLootman approved these changes

2024-11-18 16:21 UTC, merged